marathon:
  image: gdwornicki/marathon:latest
  environment:
  - MARATHON_HTTP_PORT: ${MARATHON_HTTP_PORT}
  - MARATHON_HTTPS_PORT: ${MARATHON_HTTPS_PORT}
  - MARATHON_FEATURES: ${MARATHON_FEATURES}
  - MARATHON_HOSTNAME: ${MARATHON_HOSTNAME}
  ports:
  - "${MARATHON_HTTP_PORT}:${MARATHON_HTTP_PORT}"
  - "${MARATHON_HTTPS_PORT}:${MARATHON_HTTPS_PORT}"
  privileged: true
