marathon:
  image: gdwornicki/marathon:latest
  environment:
  - HTTP_PORT=${MARATHON_HTTP_PORT}
  - MARATHON_FEATURES=${MARATHON_FEATURES}
  - MARATHON_HOSTNAME=${MARATHON_HOSTNAME}
  ports:
  - "${MARATHON_HTTP_PORT}:${MARATHON_HTTP_PORT}"
  privileged: true
  labels:
        io.rancher.container.pull_image: always
        io.rancher.container.hostname_override: container_name
