name: Ceph Jewel 10.2.7 (Rancher supported)
description: |
    Ceph Storage is open, software-defined storage designed for object storage and cloud infrastructures
version: 10.2.7-jewel
category: Storage
