name: Mesosphere Mesos
description: Default Mesosphere Mesos template
stacks:
  - name: mesos
    templateId: '*:infra*mesosphere-mesos'
  - name: network-services
    templateId: '*:infra*network-services'
  - name: ipsec
    templateId: '*:infra*ipsec'
  - name: scheduler
    templateId: '*:infra*scheduler'
  - name: healthcheck
    templateId: '*:infra*healthcheck'
