version: '2'
services:
    postgres-xl-gtm:
        image: gdwornicki/postgres-xl-gtm:9.5-stable
        volumes:
        - ${VOLUME}:/var/lib/pgxl
        environment:
        - PG_HOST=0.0.0.0 
        - PG_NODE=gtm-1 
        - PG_PORT=${PG_PORT}
        - PGDATA=/var/lib/pgxl/gtm
        labels:
            io.rancher.container.pull_image: always
            io.rancher.container.hostname_override: container_name
            io.rancher.scheduler.affinity:host_label: io.rancher.scheduler.database.cluster.gtm=${HOST_LABEL}
volumes:
    ${VOLUME}:
        driver: $DRIVER
