.catalog:
  version: v1.4.5
  minimum_rancher_version: v1.2.0-pre4-rc1
  questions:
  - variable: MARATHON_HTTP_PORT
    description: Port to expose Marathon on.
    label: Marathon Port
    required: true
    type: int
    default: 8080
  - variable: MARATHON_HTTPS_PORT
    description: Port to expose Marathon SSL on.
    label: Marathon Port
    required: true
    type: int
    default: 8443
  - variable: MARATHON_HOSTNAME
    description: Marathon hostname to use
    label: Marathon Hostname
    required: true
    type: string
    default: marathon.mesos
  - variable: MARATHON_FEATURES
    description: Marathon extra features to use
    label: Marathon Features (comma seperated)
    required: true
    type: string
    default: external_volumes
marathon:
  scale: 1
  health_check:
    port: ${MARATHON_HTTP_PORT}
    interval: 3000
    unhealthy_threshold: 2
    healthy_threshold: 2
    request_line: '/'
  health_check:
    port: ${MARATHON_HTTPS_PORT}
    interval: 3000
    unhealthy_threshold: 2
    healthy_threshold: 2
    request_line: '/'
    response_timeout: 2000
