version: '2'
services:
    ceph-osd:
        image: gdwornicki/ceph-osd:luminous
        cap_add:
        - SYS_PTRACE
        network_mode: "host"
        privileged: true
        environment:
        - ZOO_STACK=${ZOO_STACK}
        - ZOO_SERVICES=${ZOO_SERVICES}
        - ZOO_PORT=${ZOO_PORT}
        tty: true
        labels: 
            io.rancher.container.pull_image: always 
            io.rancher.container.hostname_override: container_name
            io.rancher.scheduler.affinity:host_label: io.rancher.scheduler.ceph.osd.label=${HOST_LABEL}
            io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
