version: '2'
services:
    ceph-mon:
        image: gdwornicki/ceph-mon:jewel 
        cap_add:
        - SYS_PTRACE
        network_mode: "host"
        privileged: true
        environment:
        - ZOO_STACK=${ZOO_STACK}
        - ZOO_SERVICES=${ZOO_SERVICES}
        - ZOO_PORT=${ZOO_PORT}
        labels: 
            io.rancher.container.pull_image: always 
            io.rancher.container.hostname_override: container_name
            io.rancher.scheduler.affinity:host_label: io.rancher.scheduler.ceph.mon.cluster=${HOST_LABEL}
            io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
        health_check:
            port: 6789
            interval: 2000
            initializing_timeout: 60000
            unhealthy_threshold: 3
            strategy: recreate
            healthy_threshold: 2
            response_timeout: 2000
