version: '2'
services:
    ceph-mon:
        image: gdwornicki/ceph-mon:jewel 
        volumes: 
        - ${VOLUME}:/opt/ceph
        labels: 
            io.rancher.container.pull_image: always 
            io.rancher.container.hostname_override: container_name
            io.rancher.scheduler.affinity:host_label: io.rancher.scheduler.ceph.mon.cluster=${HOST_LABEL}
volumes:
    ${VOLUME}:
        drivers: rexray
