version: '2'
services:
    ceph-mon-sidekick:
        image: gdwornicki/ceph-mon:jewel
        volumes:
        - ${VOLUME}:/opt/ceph
        environment:
        - BOOTSTRAP=true
        - JOURNAL_SIZE=${JOURNAL_SIZE}
        - POOL_DEFAULT_SIZE=${POOL_DEFAULT_SIZE}
        - POOL_DEFAULT_MIN_SIZE=${POOL_DEFAULT_MIN_SIZE}
        - POOL_DEFAULT_PG_NUM=${POOL_DEFAULT_PG_NUM}
        - POOL_DEFAULT_PGP_NUM=${POOL_DEFAULT_PGP_NUM}
        labels:
            io.rancher.container.pull_image: always
            io.rancher.container.hostname_override: container_name
    ceph-mon:
        image: gdwornicki/ceph-mon:jewel 
        volumes: 
        - ${VOLUME}:/opt/ceph
        labels: 
            io.rancher.container.pull_image: always 
            io.rancher.container.hostname_override: container_name
            io.rancher.sidekicks: ceph-mon-sidekick
volumes:
    - ${VOLUME}
