version: '2'
services:
    ceph-mon:
        image: gdwornicki/ceph-mon:jewel 
        volumes: 
        - ${VOLUME}:/opt/ceph
        labels: 
            io.rancher.container.pull_image: always 
            io.rancher.container.hostname_override: container_name
volumes:
    ${VOLUME}:
        drivers: rexray
