version: '2'
services:
    ceph-mon:
        image: gdwornicki/ceph-mon:jewel 
        cap_add:
        - SYS_PTRACE
        volumes: 
        - ${VOLUME}:/opt/ceph
        labels: 
            io.rancher.container.pull_image: always 
            io.rancher.container.hostname_override: container_name
            io.rancher.scheduler.affinity:host_label: io.rancher.scheduler.ceph.mon.cluster=${HOST_LABEL}
            io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
volumes:
    ${VOLUME}:
        driver: rancher-nfs
        external: true
