version: '2'
services:
    postgres-bdr:
        image: gdwornicki/postgres-bdr:9.4
        ports: 
        - "${PORT}:5432"
        volumes:
        - ${VOLUME}:/var/lib/postgresql/9.4/data
        environment:
        - RANCHER_ENABLED=1
        - RANCHER_CLEANUP_TIME=${RANCHER_CLEANUP_TIME}
        - MAX_CONNECTIONS=${MAX_CONNECTIONS}
        - MAX_WAL_SENDERS=${MAX_WAL_SENDERS}
        - MAX_REPLICATION_SLOTS=${MAX_REPLICATION_SLOTS}
        - MAX_WORKER_PROCESSES=${MAX_WORKER_PROCESSES}
        - ENABLE_LOGGING=${ENABLE_LOGGING}
        - LOG_ERROR_VERBOSITY=${LOG_ERROR_VERBOSITY}
        - LOG_MIN_MESSAGES=${LOG_MIN_MESSAGES}
        - LOG_LINE_PREFIX=${LOG_LINE_PREFIX}
        - ENABLE_CONFLICT_OPTIONS=${ENABLE_CONFLICT_OPTIONS}
        - DEFAULT_APPLY_DELAY=${DEFAULT_APPLY_DELAY}
        - LOG_CONFLICTS_TO_TABLE=${LOG_CONFLICTS_TO_TABLE}
        - DBNAME=${DBNAME}
        - DBUSER=${DBUSER}
        - DBPASS=${DBPASS} 
        - DBAPASS=${DBAPASS}
        - DOCKER_IP=172.17.0.1/32
        - CLUSTER_CIDR=${CLUSTER_CIDR}
        - IMPORT_DBDATA_LOCATION=${IMPORT_DBDATA_LOCATION}
        - IMPORT_DBDATA=${IMPORT_DBDATA}
        labels:
            io.rancher.container.pull_image: always
            io.rancher.container.hostname_override: container_name
            io.rancher.scheduler.affinity:host_label: io.rancher.scheduler.database.cluster=${HOST_LABEL}
volumes:
    ${VOLUME}:
        driver: local
