version: '2'
services:
    sonarqube:
        image: gdwornicki/sonarqube:6.5-rancher-secret
        ports: 
        - "${PORT}:9000"
        - "${PORT2}:9002"
        environment:
        - POSTGRE_STACK=${POSTGRE_STACK}
        - POSTGRE_SERVICE=${POSTGRE_SERVICE}
        - SONARQUBE_JDBC_USERNAME_FILE=/run/secrets/sonar.jdbc.username
        - SONARQUBE_JDBC_PASSWORD_FILE=/run/secrets/sonar.jdbc.password
        - SONARQUBE_HTTP_PROXYUSER_FILE=/run/secrets/http.proxyUser
        - SONARQUBE_HTTP_PROXYPASSWORD_FILE=/run/secrets/http.proxyPassword
        - SONARQUBE_JDBC_DATABASE=${SONARQUBE_JDBC_DATABASE}
        - SONARQUBE_HTTP_PROXYHOST=${SONARQUBE_HTTP_PROXYHOST}
        - SONARQUBE_HTTP_PROXYPORT=${SONARQUBE_HTTP_PROXYPORT}
        - SONARQUBE_AUTH_NTLM_DOMAIN=${SONARQUBE_AUTH_NTLM_DOMAIN}
        volumes:
        - ${VOLUME}:/opt/sonarqube/extensions
        - ${VOLUME2}:/opt/sonarqube/logs
        secrets:
          - sonar.jdbc.username
          - sonar.jdbc.password
          - http.proxyUser
          - http.proxyPassword
          - sonar.properties
        tmpfs:
          - /opt/sonarqube/temp
        labels:
            io.rancher.container.pull_image: always
            io.rancher.container.hostname_override: container_name
volumes:
    ${VOLUME}:
        driver: local
    ${VOLUME2}:
        driver: local
secrets:
    sonar.jdbc.username:
        external: true
    sonar.jdbc.password:
        external: true
    http.proxyUser:
        external: true
    http.proxyPassword:
        external: true
    sonar.properties:
        external: true
