version: '2'
services:
    sonarqube:
        image: gdwornicki/sonarqube:6.5-rancher
        ports: 
        - "${PORT}:9000"
        - "${PORT2}:9002"
        environment:
        - SONARQUBE_JDBC_USERNAME_FILE=/run/secrets/sonar.jdbc.username
        - SONARQUBE_JDBC_PASSWORD_FILE=/run/secrets/sonar.jdbc.password
        - SONARQUBE_HTTP_PROXYUSER_FILE=/run/secrets/http.proxyUser
        - SONARQUBE_HTTP_PROXYPASSWORD_FILE=/run/secrets/http.proxyPassword
        - SONARQUBE_LDAP_BINDDN_FILE=/run/secrets/ldap.bindDn
        - SONARQUBE_LDAP_BINDPASSWORD_FILE=/run/secrets/ldap.bindPassword
        - SONARQUBE_JDBC_DATABASE=${SONARQUBE_JDBC_DATABASE}
        - SONARQUBE_HTTP_PROXYHOST=${SONARQUBE_HTTP_PROXYHOST}
        - SONARQUBE_HTTP_PROXYPORT=${SONARQUBE_HTTP_PROXYPORT}
        - SONARQUBE_AUTH_NTLM_DOMAIN=${SONARQUBE_AUTH_NTLM_DOMAIN}
        - SONARQUBE_SECURITY_REALM=${SONARQUBE_SECURITY_REALM}
        - SONARQUBE_LDAP_URL=${SONARQUBE_LDAP_URL}
        - SONARQUBE_LDAP_USER_BASEDN=${SONARQUBE_LDAP_USER_BASEDN}
        - SONARQUBE_LDAP_USER_REQUEST=${SONARQUBE_LDAP_USER_REQUEST}
        - SONARQUBE_LDAP_GROUP_BASEDN=${SONARQUBE_LDAP_GROUP_BASEDN}
        - SONARQUBE_LDAP_GROUP_REQUEST=${SONARQUBE_LDAP_GROUP_REQUEST}
        - SONARQUBE_LDAP_GROUP_IDATTRIBUTE=${SONARQUBE_LDAP_GROUP_IDATTRIBUTE}
        volumes:
        - ${VOLUME}:/opt/sonarqube/extensions
        - ${VOLUME2}:/opt/sonarqube/logs
        secrets:
          - sonar.jdbc.username
          - sonar.jdbc.password
          - http.proxyUser
          - http.proxyPassword
          - ldap.bindDn
          - ldap.bindPassword
        tmpfs:
          - /opt/sonarqube/temp
        labels:
            io.rancher.container.pull_image: always
            io.rancher.container.hostname_override: container_name
volumes:
    ${VOLUME}:
        driver: local
    ${VOLUME2}:
        driver: local
secrets:
    sonar.jdbc.username:
        external: true
    sonar.jdbc.password:
        external: true
    http.proxyUser:
        external: true
    http.proxyPassword:
        external: true
    ldap.bindDn:
        external: true
    ldap.bindPassword:
        external: true
