version: '2.v2'
services:
    sonarqube:
        image: gdwornicki/sonarqube:6.5-rancher-secret-v2
        ports: 
        - "${PORT}:9000"
        - "${PORT2}:9002"
        environment:
        - POSTGRE_STACK=${POSTGRE_STACK}
        - POSTGRE_SERVICE=${POSTGRE_SERVICE}
        - SONARQUBE_JDBC_USERNAME_FILE=/run/secrets/sonar.jdbc.username
        - SONARQUBE_JDBC_PASSWORD_FILE=/run/secrets/sonar.jdbc.password
        - SONARQUBE_HTTP_PROXYUSER_FILE=/run/secrets/http.proxyUser
        - SONARQUBE_HTTP_PROXYPASSWORD_FILE=/run/secrets/http.proxyPassword
        - SONARQUBE_JDBC_DATABASE=${SONARQUBE_JDBC_DATABASE}
        - SONARQUBE_HTTP_PROXYHOST=${SONARQUBE_HTTP_PROXYHOST}
        - SONARQUBE_HTTP_PROXYPORT=${SONARQUBE_HTTP_PROXYPORT}
        - SONARQUBE_AUTH_NTLM_DOMAIN=${SONARQUBE_AUTH_NTLM_DOMAIN}
        - ldap.bindDn=/run/secrets/ldap.bindDn
        - ldap.bindPassword=/run/secrets/ldap.bindPassword
        - ldap.group.baseDn=/run/secrets/ldap.group.baseDn
        - ldap.group.idAttribute=/run/secrets/ldap.group.idAttribute
        - ldap.group.request=/run/secrets/ldap.group.request
        - ldap.url=/run/secrets/ldap.url
        - ldap.user.baseDn=/run/secrets/ldap.user.baseDn
        - ldap.user.request=/run/secrets/ldap.user.request
        - sonar.security.realm=/run/secrets/sonar.security.realm
        volumes:
        - ${VOLUME}:/opt/sonarqube/extensions
        - ${VOLUME2}:/opt/sonarqube/logs
        secrets:
          - sonar.jdbc.username
          - sonar.jdbc.password
          - http.proxyUser
          - http.proxyPassword
          - ldap.bindDn
          - ldap.bindPassword
          - ldap.group.baseDn
          - ldap.group.idAttribute
          - ldap.group.request
          - ldap.url
          - ldap.user.request
          - ldap.user.baseDn
sonar.security.realm
        tmpfs:
          - /opt/sonarqube/temp:exec
        labels:
            io.rancher.container.pull_image: always
            io.rancher.container.hostname_override: container_name
volumes:
    ${VOLUME}:
        driver: local
    ${VOLUME2}:
        driver: local
secrets:
    sonar.jdbc.username:
        external: true
    sonar.jdbc.password:
        external: true
    http.proxyUser:
        external: true
    http.proxyPassword:
        external: true
    sonar.properties:
        external: true
