version: '2'
services:
    sonarqube:
        image: gdwornicki/sonarqube:6.5-rancher
        ports: 
        - "${PORT}:9000"
        - "${PORT2}:9002"
        environment:
        - SONARQUBE_JDBC_USERNAME_FILE=/run/secrets/${SONARQUBE_JDBC_USERNAME}
        - SONARQUBE_JDBC_PASSWORD_FILE=/run/secrets/${SONARQUBE_JDBC_PASSWORD}
        - POSTGRE_DBNAME_FILE=/run/secrets/${POSTGRE_DBNAME}
        volumes:
        - ${VOLUME}:/opt/sonarqube
        secrets:
          - ${SONARQUBE_JDBC_USERNAME_FILE}
          - ${SONARQUBE_JDBC_PASSWORD_FILE}
          - ${POSTGRE_DBNAME_FILE}
        labels:
            io.rancher.container.pull_image: always
            io.rancher.container.hostname_override: container_name
volumes:
    ${VOLUME}:
        driver: local
secrets:
    ${SONARQUBE_JDBC_USERNAME_FILE}:
        external: true
    ${SONARQUBE_JDBC_PASSWORD_FILE}:
        external: true
    ${POSTGRE_DBNAME_FILE}:
        external: true
