version: '2'
services:
    sonarqube:
        image: gdwornicki/sonarqube:6.5-rancher-secret
        ports: 
        - "${PORT}:9000"
        - "${PORT2}:9002"
        volumes:
        - ${VOLUME}:/opt/sonarqube
        secrets:
          - sonar.properties
        labels:
            io.rancher.container.pull_image: always
            io.rancher.container.hostname_override: container_name
volumes:
    ${VOLUME}:
        driver: local
secrets:
    sonar.properties:
        external: true
