version: '2'
services:
    sonarqube:
        image: gdwornicki/sonarqube:6.5-rancher
        ports: 
        - "${PORT}:9000"
        - "${PORT2}:9002"
        environment:
        - SONARQUBE_JDBC_USERNAME_FILE=/run/secrets/sonar.username
        - SONARQUBE_JDBC_PASSWORD_FILE=/run/secrets/sonar.password
        - POSTGRE_DBNAME_FILE=/run/secrets/sonar.database
        volumes:
        - ${VOLUME}:/opt/sonarqube
        secrets:
          - sonar.username
          - sonar.password
          - sonar.database
        labels:
            io.rancher.container.pull_image: always
            io.rancher.container.hostname_override: container_name
volumes:
    ${VOLUME}:
        driver: local
secrets:
    sonar.username:
        external: true
    sonar.password:
        external: true
    sonar.database:
        external: true
