.catalog:
  name: "SonarQube"
  version: "6.5-rancher-secret-v2"
  description: "Open Source platform for continous inspection of code quality"
  questions:
    - variable: "PORT"
      label: "Default 9000"
      description: "Port number"
      default: 9000
      type: "int"
    - variable: "PORT2"
      label: "Default 9092"
      description: "Port number"
      default: 9092
      type: "int"
    - variable: "VOLUME"
      label: "default: volume"
      description: "Volume name for Sonar Qube extensions"
      default: "volume"
      type: "string"
    - variable: "VOLUME2"
      label: "default: volume2"
      description: "Volume name for Sonar Qube logs"
      default: "volume2"
      type: "string"
    - variable: "POSTGRE_STACK"
      label: "default: postgre-bdr"
      description: "Postgresql stack name"
      default: "postgre-bdr"
      type: "string"
    - variable: "POSTGRE_SERVICE"
      label: "Default: postgres-bdr"
      description: "Postgresql service name"
      default: "postgres-bdr"
      type: "string"
    - variable: "SONARQUBE_JDBC_DATABASE"
      label: "Database name"
      default: ""
      type: "string"
      required: true
    - variable: "SONARQUBE_HTTP_PROXYHOST"
      label: "Proxy hostname"
      default: ""
      type: "string"
    - variable: "SONARQUBE_HTTP_PROXYPORT"
      label: "Proxy port number"
      default: ""
      type: "int"
    - variable: "SONARQUBE_HTTP_AUTH_NTLM_DOMAIN"
      label: "NTLM auth domain"
      default: ""
      type: "string"
