version: '2'
services:
    postgres-xl-coord:
        image: gdwornicki/postgres-xl-coord:9.5-stable
        volumes:
        - ${VOLUME}:/var/lib/pgxl
        environment:
        - PG_NODE=coord-1 
        - PG_PORT=${PG_PORT}
        - PG_NET_CLUSTER=${PG_NET_CLUSTER}
        - PG_HOST=0.0.0.0
        - PGDATA=/var/lib/pgxl/coord
        - PG_GTM_SERVICE=${PG_GTM_SERVICE}
        labels:
            io.rancher.container.pull_image: always
            io.rancher.container.hostname_override: container_name
            io.rancher.scheduler.affinity:host_label: io.rancher.scheduler.database.cluster.coord=${HOST_LABEL}
volumes:
    ${VOLUME}:
        driver: $DRIVER
