name: Mesosphere Mesos
description: Default Mesosphere Mesos template
stacks:
  - name: mesos
    templateId: 'tmpl-catalog:infra*mesosphere-mesos'
  - name: network-services
    templateId: 'tmpl-catalog:infra*network-services'
  - name: ipsec
    templateId: 'tmpl-catalog:infra*ipsec'
  - name: scheduler
    templateId: 'tmpl-catalog:infra*scheduler'
  - name: healthcheck
    templateId: 'tmpl-catalog:infra*healthcheck'
